version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: crud-app-db
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: crud-db
       MYSQL_USER: appuser

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
volumes:
  mysql-data: